# Generated by Django 3.0.5 on 2020-04-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productDesc',
            field=models.CharField(default='Product Disc', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='productLink',
            field=models.CharField(default='Product Link', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='productName',
            field=models.CharField(default='Product Name', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='productPrice',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='productSite',
            field=models.CharField(default='Product Site', max_length=100),
        ),
    ]
